name: Gradle Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
          cache: gradle
      - name: Check coverage metrics
        run: ./gradlew koverVerify
